global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
  - job_name: 'custom-app'
    static_configs:
      - targets: ['custom-app:8000']